name: Scheduled Scrape Job

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check-and-scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Check for other active runs of this workflow
      run: |
        echo "Checking for in-progress workflows..."
        repo="${{ github.repository }}"
        token="${{ secrets.GITHUB_TOKEN }}"
    
        # Get the workflow file name from the GitHub context
        workflow_file=$(basename "${GITHUB_WORKFLOW_REF}")
    
        active=$(curl -s -H "Authorization: token $token" \
          "https://api.github.com/repos/$repo/actions/workflows/$workflow_file/runs?branch=${{ github.ref_name }}&status=in_progress" \
          | jq '[.workflow_runs[] | select(.id != '${{ github.run_id }}')] | length')
    
        echo "Active runs: $active"
    
        if [ "$active" -gt 0 ]; then
          echo "Another run is active. Exiting gracefully."
          exit 0
        fi


    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install

    - name: Run scraper
      env:
        ROBINHOOD_USERNAME: ${{ secrets.ROBINHOOD_USERNAME }}
        ROBINHOOD_PASSWORD: ${{ secrets.ROBINHOOD_PASSWORD }}
        ROBINHOOD_URL: ${{ secrets.ROBINHOOD_URL }}
        FLEX_USERNAME: ${{ secrets.FLEX_USERNAME }}
        FLEX_PASSWORD: ${{ secrets.FLEX_PASSWORD }}
        FLEX_URL: ${{ secrets.FLEX_URL }}
        SERVER_URL: ${{ secrets.SERVER_URL }}
      run: node scrape.js
