name: Scheduled Scrape Job

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

concurrency:
  group: scheduled-scrape
  cancel-in-progress: false

jobs:
  check-and-scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install

    - name: Run scraper
      env:
        ROBINHOOD_USERNAME: ${{ secrets.ROBINHOOD_USERNAME }}
        ROBINHOOD_PASSWORD: ${{ secrets.ROBINHOOD_PASSWORD }}
        ROBINHOOD_URL: ${{ secrets.ROBINHOOD_URL }}
        FLEX_USERNAME: ${{ secrets.FLEX_USERNAME }}
        FLEX_PASSWORD: ${{ secrets.FLEX_PASSWORD }}
        FLEX_URL: ${{ secrets.FLEX_URL }}
        SERVER_URL: ${{ secrets.SERVER_URL }}
      run: node scrape.js
