name: Scheduled Scrape Job

on:
  schedule:
    - cron: '*/5 * * * *'   # every hour
  workflow_dispatch:         # also allow manual trigger

jobs:
  check-and-scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Check for active workflows
      id: check
      run: |
        echo "Checking for in-progress workflows..."
        repo="${{ github.repository }}"
        token="${{ secrets.GITHUB_TOKEN }}"
        active=$(curl -s -H "Authorization: token $token" \
          "https://api.github.com/repos/$repo/actions/runs?status=in_progress" \
          | jq '[.workflow_runs[] | select(.name != "Scheduled Scrape Job")] | length')

        echo "Active workflows (excluding this one): $active"

        if [ "$active" -gt 0 ]; then
          echo "Other workflows are running. Skipping this run."
          exit 0
        fi

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install

    - name: Run scraper
      env:
        ROBINHOOD_USERNAME: ${{ secrets.ROBINHOOD_USERNAME }}
        ROBINHOOD_PASSWORD: ${{ secrets.ROBINHOOD_PASSWORD }}
        ROBINHOOD_URL: ${{ secrets.ROBINHOOD_URL }}
        FLEX_USERNAME: ${{ secrets.FLEX_USERNAME }}
        FLEX_PASSWORD: ${{ secrets.FLEX_PASSWORD }}
        FLEX_URL: ${{ secrets.FLEX_URL }}
        SERVER_URL: ${{ secrets.SERVER_URL }}
      run: node scrape.js
